import 'package:flutter/material.dart';

class MaterialTheme {
  // Extended colors
  static Color colorGreen = Colors.green[700]!;
  static Color colorBlue = Color(0xFF3b82f6);
  static Color colorYellow = Color(0xFFfacc15);

  static ThemeData lightThemeData() {
    return ThemeData(
      brightness: Brightness.light,
      fontFamily: 'Raleway',
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xffFF3B1E),
        surfaceTint: Color(0xffbc1700),
        onPrimary: Color(0xffffffff),
        primaryContainer: Color(0xffe32508),
        onPrimaryContainer: Color(0xfffffbff),
        secondary: Color(0xffab3522),
        onSecondary: Color(0xffffffff),
        secondaryContainer: Color(0xffff7259),
        onSecondaryContainer: Color(0xff6f0900),
        tertiary: Color(0xff7d5400),
        onTertiary: Color(0xffffffff),
        tertiaryContainer: Color(0xff9e6a00),
        onTertiaryContainer: Color(0xfffffbff),
        error: Color(0xffba1a1a),
        onError: Color(0xffffffff),
        errorContainer: Color(0xffffdad6),
        onErrorContainer: Color(0xff93000a),
        surface: Color(0xfffff8f6),
        onSurface: Color(0xff291714),
        onSurfaceVariant: Color(0xff5d3f3a),
        outline: Color(0xff926f68),
        outlineVariant: Color(0xffe7bdb5),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xff402b27),
        inversePrimary: Color(0xffffb4a6),
        primaryFixed: Color(0xffffdad3),
        onPrimaryFixed: Color(0xff3f0300),
        primaryFixedDim: Color(0xffffb4a6),
        onPrimaryFixedVariant: Color(0xff900f00),
        secondaryFixed: Color(0xffffdad3),
        onSecondaryFixed: Color(0xff3f0300),
        secondaryFixedDim: Color(0xffffb4a6),
        onSecondaryFixedVariant: Color(0xff891d0c),
        tertiaryFixed: Color(0xffffddb0),
        onTertiaryFixed: Color(0xff291800),
        tertiaryFixedDim: Color(0xffffba48),
        onTertiaryFixedVariant: Color(0xff614000),
        surfaceDim: Color(0xfff4d3cc),
        surfaceBright: Color(0xfffff8f6),
        surfaceContainerLowest: Color(0xffffffff),
        surfaceContainerLow: Color(0xfffff0ee),
        surfaceContainer: Color(0xffffe9e5),
        surfaceContainerHigh: Color(0xffffe2dc),
        surfaceContainerHighest: Color(0xfffddbd5),
      ),
      useMaterial3: true,
    );
  }

  static ThemeData darkThemeData() {
    return ThemeData(
      brightness: Brightness.dark,
      useMaterial3: true,
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffFF3B1E),
        surfaceTint: Color(0xffbc1700),
        onPrimary: Color(0xffffffff),
        primaryContainer: Color(0xffd71c00),
        onPrimaryContainer: Color(0xffffffff),
        secondary: Color(0xff710a00),
        onSecondary: Color(0xffffffff),
        secondaryContainer: Color(0xffbf432e),
        onSecondaryContainer: Color(0xffffffff),
        tertiary: Color(0xff4c3100),
        onTertiary: Color(0xffffffff),
        tertiaryContainer: Color(0xff946300),
        onTertiaryContainer: Color(0xffffffff),
        error: Color(0xff740006),
        onError: Color(0xffffffff),
        errorContainer: Color(0xffcf2c27),
        onErrorContainer: Color(0xffffffff),
        surface: Color(0xfffff8f6),
        onSurface: Color(0xff1d0d0a),
        onSurfaceVariant: Color(0xff4b2f2a),
        outline: Color(0xff6a4b45),
        outlineVariant: Color(0xff87655e),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xff402b27),
        inversePrimary: Color(0xffffb4a6),
        primaryFixed: Color(0xffd71c00),
        onPrimaryFixed: Color(0xffffffff),
        primaryFixedDim: Color(0xffaa1400),
        onPrimaryFixedVariant: Color(0xffffffff),
        secondaryFixed: Color(0xffbf432e),
        onSecondaryFixed: Color(0xffffffff),
        secondaryFixedDim: Color(0xff9d2b19),
        onSecondaryFixedVariant: Color(0xffffffff),
        tertiaryFixed: Color(0xff946300),
        onTertiaryFixed: Color(0xffffffff),
        tertiaryFixedDim: Color(0xff744d00),
        onTertiaryFixedVariant: Color(0xffffffff),
        surfaceDim: Color(0xffe0bfb9),
        surfaceBright: Color(0xfffff8f6),
        surfaceContainerLowest: Color(0xffffffff),
        surfaceContainerLow: Color(0xfffff0ee),
        surfaceContainer: Color(0xffffe2dc),
        surfaceContainerHigh: Color(0xfff7d5cf),
        surfaceContainerHighest: Color(0xffebcac4),
      ),
    );
  }
}
